### ISSUE TITLE
no delay

### ISSUE THREAD

**Issue by lightningorb** [PierreMarchand20/asciinema_automation#1] opened 2022-09-06 08:29 UTC
Hi,

Excellent repo. Consider posting it somewhere like HN, because right now it's not easy to find.

Is there any chance to have 0 delay? It would be useful when commands use very long text inputs as arguments.

Even with a delay of 0 and standard deviation of 0, there's still a delay.

Thanks.

**Comment by PierreMarchand20** [comment] 2022-09-06 09:30
Hi, thanks ! What is HN ? ^^'

Could you give an example ? 

The issue is probably that you are using the usual way to type a command (without any `#$ ...`), which I call a [SendShellInstruction](https://github.com/PierreMarchand20/asciinema_automation/blob/master/asciinema_automation/instruction.py#L84). In practice this means [looping over characters](https://github.com/PierreMarchand20/asciinema_automation/blob/master/asciinema_automation/instruction.py#L56-L63) and [end](https://github.com/PierreMarchand20/asciinema_automation/blob/master/asciinema_automation/instruction.py#L92) with `\n`. I guess the loop adds a minimal delay. To avoid this you can use a [SendCharacterInstruction](https://github.com/PierreMarchand20/asciinema_automation/blob/master/asciinema_automation/instruction.py#L73), for example

```
#$ sendcharacter your_command
```
but you will need to explicit "enter the command", with `#$ sendcontrol m`.

**Comment by PierreMarchand20** [comment] 2022-09-06 12:52
By the way, this kind of issues may be more relevant to [asciinema_automation](https://github.com/PierreMarchand20/asciinema_automation), which is the python package behind all the examples here.

[ascinema_playground](https://github.com/PierreMarchand20/asciinema_playground)is just a repo for my own usage of asciinema_automation, that I let public to give examples to asciinema_automation.

**Comment by lightningorb** [comment] 2022-09-09 06:40
I've switched to using environment variables. I'll try `sendcharacter` thanks.

**Comment by PierreMarchand20** [comment] 2022-09-12 20:40
What do you mean by "using environment variables"? I do not see how it can solve this issue.

I will close this issue if `sendcharacter` also does the job done.

**Comment by PierreMarchand20** [comment] 2022-11-28 08:41
Feel free to reopen the issue if needed

**Closed as completed by PierreMarchand20** 2022-11-28 08:41 UTC
